Update action.yml

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -37,11 +37,10 @@ inputs:
       default: '18'
       required: true
 runs:
-    using: 'composite'
     steps:
-      - uses: actions/checkout@v3
-        name: Generate Base64 Release Key
+      - name: Check Runner OS
+        if: ${{ runner.os != 'Linux' }}
         shell: bash
         run: |
-          echo "KEYSTORE_BASE64=$(openssl base64 < ${{ inputs.keystore_file }} | tr -d '\n')" >> "$GITHUB_OUTPUT"
-      
+          echo "::error title=⛔ error hint::Support Linux Only"
+          exit 1
