Update action.yml

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -1,99 +1,119 @@
-name: 'Quasar Play Store'
-description: 'Connect your GitHub Action workflow to Play Store'
-author: 'Anant Negi'
+# Copyright (c) Tailscale Inc & AUTHORS
+# SPDX-License-Identifier: BSD-3-Clause
+#
+name: 'Test11'
+description: 'Connect your GitHub Action workflow to Tailscale'
 branding:
-  icon: 'airplay'
+  icon: 'arrow-right-circle'
   color: 'gray-dark'
 inputs:
-  play_store_credentials:
-      description: 'Play Store Credentials'
-      default: ''
-      required: true
-  app_version:
-      description: 'App Version'
-      default: ''
-      required: true
-    package_name:
-      description: 'Package Name'
-      default: ''
-      required: true
-    alias:
-      description: 'Secrets Alias'
-      default: ''
-      required: true
-    key_store_password:
-      description: 'Secrets Key Store Password'
-      default: ''
-      required: true
-    app_track:
-      description: 'App Track'
-      default: 'internal'
-      required: true
-    build_tools_version:
-      description: 'Build Tools Version'
-      default: '33.0.2'
-      required: true
-    node_version:
-      description: 'Node Version'
-      default: '18'
-      required: true
-env:
-  APP_VERSION: ""
-  KEYSTORE_BASE64: ""  
+  authkey:
+    description: 'Your Tailscale authentication key, from the admin panel.'
+    required: false
+    deprecationMessage: 'An OAuth API client https://tailscale.com/s/oauth-clients is recommended instead of an authkey'
+  oauth-client-id:
+    description: 'Your Tailscale OAuth Client ID.'
+    required: false
+  oauth-secret:
+    description: 'Your Tailscale OAuth Client Secret.'
+    required: false
+  tags:
+    description: 'Comma separated list of Tags to be applied to nodes. The OAuth client must have permission to apply these tags.'
+    required: false
+  version:
+    description: 'Tailscale version to use.'
+    required: true
+    default: '1.42.0'
+  sha256sum:
+    description: 'Expected SHA256 checksum of the tarball.'
+    required: false
+    default: ''
+  args:
+    description: 'Optional additional arguments to `tailscale up`'
+    required: false
+    default: ''
+  tailscaled-args:
+    description: 'Optional additional arguments to `tailscaled`'
+    required: false
+    default: ''
+  hostname:
+    description: 'Fixed hostname to use.'
+    required: false
+    default: ''
 runs:
     using: 'composite'
     steps:
-      - uses: actions/checkout@v3
-      - name: Generate Base64 Release Key
+      - name: Check Runner OS
+        if: ${{ runner.os != 'Linux' }}
         shell: bash
         run: |
-          echo "KEYSTORE_BASE64=$(openssl base64 < ${{ inputs.keystore_file }} | tr -d '\n')" >> "$GITHUB_OUTPUT"
-      - uses: actions/setup-node@v3
-        with:
-          node-version: ${{ inputs.node_version }}  # Adjust this to your desired Node.js version
-      - name: Append v in APP_VERSION
+          echo "::error title=⛔ error hint::Support Linux Only"
+          exit 1
+      - name: Check Auth Info Empty
+        if: ${{ inputs.authkey == '' && (inputs['oauth-secret'] == '' || inputs.tags == '') }}
         shell: bash
         run: |
-          echo APP_VERSION="v${{ inputs.app_version }}" >> "$GITHUB_ENV"
-      - name: Inputs Print
+          echo "::error title=⛔ error hint::OAuth identity empty, Maybe you need to populate it in the Secrets for your workflow, see more in https://docs.github.com/en/actions/security-guides/encrypted-secrets and https://tailscale.com/s/oauth-clients"
+          exit 1
+      - name: Download Tailscale
         shell: bash
-        run: |
-          echo "Package Name: ${{ inputs.package_name }}"
-          echo "App Version: ${{ env.APP_VERSION }}"
-          echo "Track: ${{ inputs.app_track }}"
-          echo "Bundle Tools Version: ${{ inputs.build_tools_version }}"
-      - uses: actions/cache@v3
-        with:
-          key: node-dependencies
-          path: node_modules
-      - if: steps.cache-dependencies.outputs.cache-hit != 'true'
-        shell: bash
-        run: |
-          yarn global add @quasar/cli
-          yarn global add cordova
-          yarn install
-      - name: Build Mobile Builder
-        shell: bash
-        run: quasar build -m cordova -T android
-      - uses: r0adkll/sign-android-release@v1
-        name: Sign app APK
-        id: sign_app
-        with:
-          releaseDirectory: src-cordova/platforms/android/app/build/outputs/bundle/release
-          signingKeyBase64: ${{ env.KEYSTORE_BASE64 }}
-          alias: ${{ inputs.alias }}
-          keyStorePassword: ${{ inputs.key_store_password }}
+        id: download
         env:
-          BUILD_TOOLS_VERSION: ${{ inputs.build_tools_version }}
-      - uses: actions/upload-artifact@v3
-        with:
-          name: $ - $ - $ - App bundle(s) AAB release generated
-          path: $/build/outputs/bundle/release/
-      - uses: r0adkll/upload-google-play@v1
-        with:
-          serviceAccountJsonPlainText: ${{ inputs.play_store_credentials }}
-          track: ${{ inputs.app_track }}
-          packageName: ${{ inputs.package_name }}
-          releaseName: ${{ env.APP_VERSION }}
-          releaseFiles: ${{ steps.sign_app.outputs.signedReleaseFile }}
-          debugSymbols: src-cordova/platforms/android/app/build/intermediates/merged_native_libs/release/out/lib
+          VERSION: ${{ inputs.version }}
+          SHA256SUM: ${{ inputs.sha256sum }}
+        run: |
+          if [ ${{ runner.arch }} = "ARM64" ]; then
+            TS_ARCH="arm64"
+          elif [ ${{ runner.arch }} = "ARM" ]; then
+            TS_ARCH="arm"
+          elif [ ${{ runner.arch }} = "X86" ]; then
+            TS_ARCH="386"
+          elif [ ${{ runner.arch }} = "X64" ]; then
+            TS_ARCH="amd64"
+          else
+            TS_ARCH="amd64"
+          fi
+          MINOR=$(echo "$VERSION" | awk -F '.' {'print $2'})
+          if [ $((MINOR % 2)) -eq 0 ]; then
+            URL="https://pkgs.tailscale.com/stable/tailscale_${VERSION}_${TS_ARCH}.tgz"
+          else
+            URL="https://pkgs.tailscale.com/unstable/tailscale_${VERSION}_${TS_ARCH}.tgz"
+          fi
+          if ! [[ "$SHA256SUM" ]] ; then
+            SHA256SUM="$(curl -H user-agent:tailscale-github-action -L "${URL}.sha256")"
+          fi
+          curl -H user-agent:tailscale-github-action -L "$URL" -o tailscale.tgz --max-time 300
+          echo "Expected sha256: $SHA256SUM"
+          echo "Actual sha256: $(sha256sum tailscale.tgz)"
+          echo "$SHA256SUM  tailscale.tgz" | sha256sum -c
+          tar -C /tmp -xzf tailscale.tgz
+          rm tailscale.tgz
+          TSPATH=/tmp/tailscale_${VERSION}_${TS_ARCH}
+          sudo mv "${TSPATH}/tailscale" "${TSPATH}/tailscaled" /usr/bin
+      - name: Start Tailscale Daemon
+        shell: bash
+        env:
+          ADDITIONAL_DAEMON_ARGS: ${{ inputs.tailscaled-args }}
+        run: |
+          sudo -E tailscaled --state=mem: ${ADDITIONAL_DAEMON_ARGS} 2>~/tailscaled.log &
+          # And check that tailscaled came up. The CLI will block for a bit waiting
+          # for it. And --json will make it exit with status 0 even if we're logged
+          # out (as we will be). Without --json it returns an error if we're not up.
+          sudo -E tailscale status --json >/dev/null
+      - name: Connect to Tailscale
+        shell: bash
+        env:
+          TAILSCALE_AUTHKEY: ${{ inputs.authkey }}
+          ADDITIONAL_ARGS: ${{ inputs.args }}
+          HOSTNAME: ${{ inputs.hostname }}
+          TS_EXPERIMENT_OAUTH_AUTHKEY: true
+        run: |
+          if [ -z "${HOSTNAME}" ]; then
+            HOSTNAME="github-$(cat /etc/hostname)"
+          fi
+          if [ -n "${{ inputs['oauth-secret'] }}" ]; then
+            TAILSCALE_AUTHKEY="${{ inputs['oauth-secret'] }}?preauthorized=true&ephemeral=true"
+            TAGS_ARG="--advertise-tags=${{ inputs.tags }}"
+          fi
+          timeout 5m sudo -E tailscale up ${TAGS_ARG} --authkey=${TAILSCALE_AUTHKEY} --hostname=${HOSTNAME} --accept-routes ${ADDITIONAL_ARGS}
+          
